// modern-frameworks/lectures/01-vue-intro/examples/05-counter-angular/src/app/app.ts
import { Component, computed, signal } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <h1>Лічильник — Angular</h1>
    <p class="count">{{ count() }}</p>
    <button (click)="add()">Додати</button>
    <button (click)="clear()">Очистити</button>
    <p>{{ total() }}</p>
    <ul>
      @for (e of entries(); track e) {
        <li>{{ e }}</li>
      }
      @if (entries().length === 0) {
        <li class="empty">поки порожньо</li>
      }
    </ul>
  `,
})
export class App {
  protected readonly count = signal(0);
  protected readonly entries = signal<string[]>([]);
  protected readonly total = computed(
    () => `Записів: ${this.entries().length}`,
  );

  protected add(): void {
    const next = this.count() + 1;
    this.count.set(next);
    this.entries.update((list) => [
      `Запис ${next} о ${new Date().toLocaleTimeString('uk-UA')}`,
      ...list,
    ]);
  }

  protected clear(): void {
    this.count.set(0);
    this.entries.set([]);
  }
}

// modern-frameworks/lectures/01-vue-intro/examples/03-counter-react/src/App.jsx
import { useState } from 'react'

export default function App() {
  const [count, setCount] = useState(0)
  const [entries, setEntries] = useState([])
  const total = `Записів: ${entries.length}`

  function add() {
    const next = count + 1
    setCount(next)
    setEntries((list) => [
      `Запис ${next} о ${new Date().toLocaleTimeString('uk-UA')}`,
      ...list,
    ])
  }

  function clear() {
    setCount(0)
    setEntries([])
  }

  return (
    <>
      <h1>Лічильник — React</h1>
      <p className="count">{count}</p>
      <button onClick={add}>Додати</button>
      <button onClick={clear}>Очистити</button>
      <p>{total}</p>
      <ul>
        {entries.map((e) => <li key={e}>{e}</li>)}
        {entries.length === 0 && (
          <li className="empty">поки порожньо</li>
        )}
      </ul>
    </>
  )
}
